### ISSUE TITLE
Missing source in plugin

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-tool#103]
Currently the source code for `org.moflon.tgg.algorithm.configuration.PGSavingConfigurator` and maybe all other classes of the according plugin is not provided with the eclipse plugin.

**Comment by RolandKluge** [comment]
This is correct, we are currently not systematically providing the source code of eMoflon in the installed plugins. This has something to do with our current build process, which is unfortunately a little non-standard.

**Comment by anthonyanjorin** [comment]
What does this have to do with the build process?  I thought it's just a setting in the build.properties file (or plugin.xml) stating what should be packed in the build and what not.

**Comment by anthonyanjorin** [comment]
Yes, for the moment we could just pack all the source code in every plugin (I wouldn't care).  Debugging right now is seriously a pain in the ass.

**Comment by RolandKluge** [comment]
When inspecting the build.properties files, I recognize that /src, /gen have been removed from them durign a previous debugging. Since it is not so probable that we fix the whole build process of eMoflon in the next weeks, I re-added them in @974b99c to support debugging.
