### ISSUE TITLE
Find a name for the textual successor of SDMs in eMoflon

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#107]
@anthonyanjorin @erhanleblebici @gervarro @gkulcsar 

As you may now, I am not very pleased with naming the new textual syntax MOSL-SDM because it will (definitely) have not much in common with SDMs.

I had a short discussion with Andy and, for him, it would be OK to name the new language MOSL-GT.

Does anybody disagree with this name?

**Comment by anthonyanjorin** [comment]
No, I think it's fine.  I recall having a similar discussion about the name "Moflon" and an important point is that there is some value in having and keeping a known "brand".  SDM _is_ a known brand to some people, so this would be my only argument in favour of keeping some variation on the name.  But if Andy doesn't mind ... ;)

**Comment by RolandKluge** [comment]
OK, since the work on the textual syntax will start from today, we take MOSL-GT for now.
