### ISSUE TITLE
ECore Visualization doesnot work in deployment

### ISSUE THREAD

**Issue by SaschaEdwinZander** [eMoflon/emoflon-tool#110]
if I want to look at the drawing from Ecore Visualization I get an IllegalArgumentException:

```
ERROR [language.EMoflonDiagramTextProvider::31] - Exception during visualization of PMethodToEOperation : EClass: Reason: file:/C:/eclipse/EMF/neonNeu/eclipse/plugins/org.moflon.ide.visualization.dot.ecore.eclassviz_1.0.0.jar!//model/Eclassviz.sma.xmi does not exist. Reason:
java.lang.IllegalArgumentException: file:/C:/eclipse/EMF/neonNeu/eclipse/plugins/org.moflon.ide.visualization.dot.ecore.eclassviz_1.0.0.jar!//model/Eclassviz.sma.xmi does not exist.
	at org.moflon.core.utilities.eMoflonEMFUtil.createFileURI(eMoflonEMFUtil.java:536)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.loadModel(SynchronizationHelper.java:516)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.loadRulesFromProject(SynchronizationHelper.java:555)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.loadRulesFromProject(SynchronizationHelper.java:582)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.<init>(SynchronizationHelper.java:238)
...
```

Is something missing in the Deployment? Or is somthing missing in the Ecore Visulization Projects? 

If I run a runtime-workspace it's working.

**Comment by RolandKluge** [comment]
> file:/C:/eclipse/EMF/neonNeu/eclipse/plugins/org.moflon.ide.visualization.dot.ecore.eclassviz_1.0.0.jar!//model/Eclassviz.sma.xmi
Is the file there? 
If you look inside the jar file, is *Eclassviz.sma.xmi* there?

The archive that is online seems to be appropriate (https://emoflon.github.io/eclipse-plugin/emoflon_2.21.0/update-site2/plugins/org.moflon.ide.visualization.dot.ecore.eclassviz_1.0.0.jar).

Maybe the // is also a problem.

**Comment by SaschaEdwinZander** [comment]
The File is there and the EClassviz.sma.xmi is inside the jar. I think there is another problem which is masking with the IllegalArgumentException.

**Comment by anthonyanjorin** [comment]
I don't think it works from inside a jar.  All the other vis projects have the option "unpack when installing" activated.  This means the .sma is in a normal folder and everything works.

**Comment by anthonyanjorin** [comment]
I might be wrong, but comparing the plugin settings (and entries in the feature project), with the other vis projects should clarify what the difference (and probably the problem) is.

**Comment by gervarro** [comment]
Files inside a jar file can be accessed by using the `archive:/` protocol (`archive:/file:///...`). I do not know the exact syntax by heart, but you can experiment with it in debug mode or check an older version (before August 2016) of the Democles plugin in eMoflon, which contained a single jar file.

On the other hand, I would completely avoid the use of the `file` protocol in Eclipse plugins, as the mapping of plugin locations to the corresponding filesystem locations is an Eclipse-internal info, which can theoretically change (due to the OSGi framework) even at runtime (e.g., updating a plugin to a newer version on-the-fly). I would recommend using the

    platform:/plugin/org.moflon.ide.visualization.dot.ecore.eclassviz/model/Eclassviz.sma.xmi

URI/URL to access files in deployed plugins.

**Comment by RolandKluge** [comment]
While I agree with Greg concerning the cleanliness of using appropriate URLs, I do not see how to quickly modify the whole 
The trick with the "Unpack" option also came to my mind.

I will deploy a new version of eMoflon later.

A key problem is that the default implementation of Synchronization helper relies on project-based paths.
To solve this problem in the future/in case of the Eclassviz, please adjust your code (and test it!) to use the following method:
```org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.loadModelFromURI(URI)```
