### ISSUE TITLE
Missing auto-completion for attributes of object variables in in MOSL-TGG

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#114]
When working through the handbook, one should specify the `CardToEntryRule` rule.

Inside the #attributeConstraints scope, the auto-completion for constraint names and object variables works perfectly!

However, attributes are not supported, e.g., `indexToLevel(partition. <Ctrl+Space>` yield nothing

**Comment by anthonyanjorin** [comment]
Thanks, @Roland:  yes, this is very annoying and there's already a FIXME in the grammar.  It's non-trivial to fix however, as our tgg metamodell has to be improved.
