### ISSUE TITLE
Align attribute constraints left in TGG Viz?

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#115]
Just a suggestion: I think it would look nicer/"calmer" if the attribute constraints were aligned left.

What do you think?

**Comment by anthonyanjorin** [comment]
Yes, why not.  And while we're at it we should also sort them (or retain the exact same sorting as in the textual concrete syntax).

**Comment by RolandKluge** [comment]
I would opt for keeping the order consistent with the text.
