### ISSUE TITLE
Towards eMoflon Modules

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#116]
Ein EMoflon Module:
- kann in einem Workspace ausgecheckt und automatisch gebaut werden
- kann mit dem workspace **gedeployt** werden (zu einer UpdateSite)
- kann automatisch installiert werden (Abhängigkeiten werden automatisch mitinstalliert)
- ist eine sinnvolle Sammlung Projekte in dem Sinne, dass sie oft zusammen geändert werden 
- besteht aus mehreren Features damit man (1) nicht alles installieren muss und (2) nicht von allem abhängen muss

---
## **eMoflon::Ecore**
- Nur Abhängigkeiten zu Ecore/EMF.  Wenn man eigentlich nur metamodellieren will aber einige Nettigkeiten von uns noch haben möchte.
- unser Projekttyp um aus einer Ecoredatei Java-Code zu generieren.  
- Injections
- unsere abstract syntax view
- eMoflon perspective
- Ecore Visualisierung (Abhängigkeit zu PlantUML, Visualisierungsframework, und daher tgg.runtime glaub ich)?
- Features:  core, ui, vis?

---
## **eMoflon::SDM**
- Projekttyp für SDMs
- metamodellprojekte für ea
- Builder für democles 
- SDM Visualisierung
- Features:  core, ui, vis

---
## **eMoflon::TGG**
- Projekttyp für tggs
- Builder für MOSL
- tgg algo und runtime 
- TGG, Delta, Matches vis
- Delta-Editor
- Features:  core, ui, vis?

**Comment by gervarro** [comment]
Paar Kommentare dazu,
* Diese Aufteilung ist durch die MocaToMoflonTransformation blockiert. Das ist ein relativ großer Aufwand, diese Transformation aufzusplitten.
* Ich bin nicht sicher, ob Injections zum Core gehören. Die Frage, ob man Injections in TGGs ohne SDMs (oder Injections allein) braucht.
* Ich würde den Core von der Visualisierung wegen der vielen externen Abhängigkeiten trennen. Das führt immer zum Ärger, wenn man Visualisierung gar nicht braucht. Z.B wenn ich etwas in der Codegenerierung ändern muss (EA + SDM), dann installiere ich (für die Entwicklung) ungern externe Module, um den Workspace fehlerfrei bauen zu können (wenn Modul = Workspace). Auf der anderen Seite finde ich Visualisierung als optionale Feature (für Deployment) völlig in Ordnung.

**Comment by anthonyanjorin** [comment]
- Ja, guter Punkt.  Ich würde auch warten bis wir EA engültig (und MocaToMoflonTransformation) los sind.  Sonst wird es echt schwierig.
- Der Vorschlag war es, Injections in eMoflon::Ecore::ui aufzunehmen, nicht eMoflon::Ecore::core.  Mein Gefühl hier ist, dass man aber als Endanwender (oder Entwickler, der von eMoflon abhängen möchte) oft Injections zusammen mit EMF-Codegen gerne hätte, aber manchmal **ohne** den Rest von eMoflon.
- Ja das stimmt - auch ein guter Punkt :(  Vielleicht doch zwei Workspaces pro Modul ermöglichen?  D.h., (1)  core und (2) ui + vis?

**Comment by RolandKluge** [comment]
I guess, this issue is now obsolete because we now have an eMoflon Core. Further decomposing the legacy eMoflon would not make sense, esp. to lack of manpower.
