### ISSUE TITLE
Integrate reachability analysis into build process

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#120]
We are currently about to integrate the reachability analysis as described in https://link.springer.com/article/10.1007%2Fs10270-013-0372-2

@gervarro FYI

**Comment by RolandKluge** [comment]
@erhanleblebici I have added a branch for our joint work to origin. 

Name: rkluge/reachability

**Comment by RolandKluge** [comment]
Code locations:
* org.moflon.sdm.runtime.democles.impl.PatternInvocationImpl.setPattern(Pattern)

**Comment by anthonyanjorin** [comment]
Has this now been completed or not?  I'll be holding a workshop in April for Girls' Day and it would be fantastic to not have eMoflon hanging for disjunct patterns

**Comment by RolandKluge** [comment]
Currently, this task is on hold due to lack of time (e.g., MOSL-GT and (I guess) Ibex).

I see that this is important and will work on it as much as possible in March.
Otherwise, we should see whether we can find a heuristic for detecting (e.g.,) disjunct patterns.

**Comment by RolandKluge** [comment]
The reachability analysis is now fully integrated an can be enabled/disabled via the eMoflon preferences page (Windows->Preferences->eMoflon)
