### ISSUE TITLE
Class Visualization doesn't show some Elements

### ISSUE THREAD

**Issue by SaschaEdwinZander** [eMoflon/emoflon-tool#135]
Class Visualization have problems with structual features like EReferences or EAttributes. These features sometimes are not shown.

**Comment by anthonyanjorin** [comment]
Please find a simple example attached.  I have identified (at least) the following problems:

1. For some classes, e.g., TGGNamedElement, the vis crashes and just shows an error message in the viewer.
2. The names of references have a strange ```..```prefix.  What is this supposed to be?  Multiplicities are either ```*```, ```0..1```,  or ```n..m``` where n and m are positive integers greater or equal to 1, and m is greater or equal to n.
3. For some elements, e.g., TGG, some references are simply missing in the vis!
4. In TGGRule attributes are missing (and self references)
5. TGGRuleCorr is missing all references
... and so on
