### ISSUE TITLE
Discouraged access in TGGFormatter

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#141]
The class TGGFormatter uses a lot of discouraged accesses. Even the inheritance from its super class is discouraged.

Do you now why this is necessary?

**Comment by anthonyanjorin** [comment]
No idea, I only remember that the formatter uses a rather "new" interface.  Maybe it hasn't been officially released yet.  The rules for discouraged access are from Xtext plugins right?

**Comment by RolandKluge** [comment]
Right, the XText guys will probably have marked the whole class as "deprecated". I just wanted to know it because a major part of the warnings in our dev workspace come from the TGGFormatter.

**Comment by RolandKluge** [comment]
It appears that the warning is a false positive: https://www.eclipse.org/forums/index.php/t/1067326/

I will merge a fix in the near future.
