### ISSUE TITLE
Potentially dangerous dependency to democles.jar in org.moflon.tgg.language

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#143]
By coincidence, I recognized that a fat-jar version of democles is still part of the Dev workspace.

While I did not experience any problems, this is a warning that the fat jar may at some point in time collide with the Democles version that is provided via moflon.target.

**Comment by RolandKluge** [comment]
The exact path is: /org.moflon.tgg.language/lib/democles.jar

**Comment by anthonyanjorin** [comment]
I think this is an old version of Democles used only for our attribute constraints.  I believe @erhanleblebici tried to replace it once with the current version and it was just too much effort.

**Comment by RolandKluge** [comment]
OK, I guess since the TGG framework are currently engineered from scratch, it makes no sense working on this issue.
