### ISSUE TITLE
SDM-CSPs are not able to handle EObjects (only EDataTypes)

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#148]

**Comment by gervarro** [comment]
What is the actual problem here?

**Comment by RolandKluge** [comment]
For instance, in my specification I have a class *Node* and would like to pass an instance of *Node* to a user-specified constraint to be able to (e.g.) extract multiple different attribute values.

**Comment by gervarro** [comment]
The original idea was (at least in the SDM compiler) to restrict CSPs to attributes, however, this still makes possible to pass several attribute values (but not the EObjects themselves). I do not know whether I understood the context, in which this problem arises.

**Comment by RolandKluge** [comment]
Ah, I understand. The rational was to keep the parameter list of complex constraints short by extracting multiple attributes inside the code that operationalizes the constraint.

Thanks for the quick explanation.
