### ISSUE TITLE
404 for handbook on TGGs

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#152]
https://emoflon.github.io/eclipse-plugin/beta/handbook/part4.pdf (link on our website) gives a 404 as of today.

**Comment by RolandKluge** [comment]
The handbook is now available as one single file. 

https://emoflon.github.io/eclipse-plugin/beta/handbook/eMoflonHandbook_2.24.0.pdf

I have adapted the website accordingly.
