### ISSUE TITLE
Set default method body handler to DEMOCLES_ATTRIBUTES if a metamodel contains CSP constraints

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#156]

**Comment by RolandKluge** [comment]
Closed in @bd17321

**Comment by gervarro** [comment]
Such a change is **extremely dangerous**, which might result in an erroneous bootstrapping in the complete code generation if someone uses a CSP in one of the core SDM modules in the future. Switching from Democles to Democles_Attribute is/might be a semantic changing step (depending on what Fred exactly implemented), if CSPs are attached to green objects, e.g., `a.x := b.y + c.z` when object variable `a` is green. The stability of the complete bootstrapping process can only be guaranteed if the configuration setting Democles is used for in the core modules.

**Comment by RolandKluge** [comment]
This change only applies to newly created projects (MoflonProjectCreator).

I think this is not problematic, is it?

**Comment by gervarro** [comment]
Sorry, I have not checked which projects it would be applied to. In this case, it is not that critical. However, note that the generated code might not be semantically equivalent in certain cases.
