### ISSUE TITLE
Constructor of DebugSynchronizationHelper

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#17]
_From @mabilov on June 23, 2015 15:49_

The constructor of DebugSynchronizationHelper class takes two parameters as arguments: Package of the correspondence model and path to the project. There is some complications with the second parameter. The problem is when the project where TGG rules are specified compiled to the jar, the SynchronizationHelper cannot longer locate the xmi file of the rules inside the jar archive. Although there is separate implementation for locating the xmi file in the jar archive, it is not called from the constructor. It would be great if there is a logic that would check if the current project path is a jar archive, then try to load from the archive instead, otherwise load from the file system.

_Copied from original issue: eMoflon/emoflon#474_

**Comment by erhanleblebici** [comment]
Unfortunately, debugging has been removed from TGGs due to the huge integration effort and its maintanence costs. We instead utilize visualizations of TGG-related data to understand what happened in a synchronization/consistency check run.
