### ISSUE TITLE
ClassCastException for returned array of ProjectUtil#remove

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#177]
While working on MOSLGTBuilder (#171), I found out that arrays returned from ProjectUtil#remove(ICommand[], int) may cause ClassCastExceptions (at runtime, of course). The problem appears to be that the returned array is actually of type Object[] instead of ICommand[].

On Stackoverflow, I found the following solution:
```
public static <T> T[] newArray(Class<T[]> type, int size) {
   return type.cast(Array.newInstance(type.getComponentType(), size));
}

// How to use: ICommand[] test = newArray(ICommand[].class, 10);
```
(https://stackoverflow.com/questions/529085/how-to-create-a-generic-array-in-java/4221845#4221845)

A simpler solution could be to create a copy of the array provided to ProjectUtil#remove (using Arrays.copyOf)

For now, I circumvent the issue by copying the resulting array manually, *but* I guess that the other builder may only suffer from this typing problem.

**Comment by gervarro** [comment]
Thanks for the bug report. I forgot to update the creation of generic arrays in the Eclipse Utils code.
The Eclipse Utils update site (http://gervarro.org/eclipse-utils/integration-2.0.0/) now contains the bug fix, so you can integrate the corresponding fixed plugin into eMoflon.

**Comment by RolandKluge** [comment]
OK, thank you.
