### ISSUE TITLE
[TGG] Optimize siblings heuristic

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#18]
_From @anthonyanjorin on July 2, 2015 7:38_

Our siblings heuristic when picking the next set of matches in the readySet is currently costly.

As it is really important for many TGGs (not only with amalgamation) it would make sense to invest some time to understand why it is so costly and how we can speed it up.  An idea would be to introduce counters, a table, or some other form of bookkeeping, so that the check does not need to be repeated all the time.

_Copied from original issue: eMoflon/emoflon#486_

**Comment by erhanleblebici** [comment]
our new collection framework Trove seems to scale well in readySet calculation and has never been the bottleneck (even not for large TGGs like the one by Sven)
