### ISSUE TITLE
Security exception due to signer information

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon-tool#180]
I get the following security exception for example in TGG0-Tests:
**signer information does not match signer information of other classes in the same package**

I guess the problem is the following:
The package csp.constraints in tgg.language-Plugin is signed. User-Defines CSP-constraints, however, are specified in a user project under the same package (csp.constraints). So we have signed eMoflon classes + unsigned user classes in the same package.

In fact, situations where a user project has same packages as eMoflon plugins are not rare. What can we do about this?

**Comment by RolandKluge** [comment]
This appears to be a major problem.

Strictly speaking, no user of eMoflon should create "org.moflon" packages, but I guess this has been our convention for a long time. 

Apart form the TGG-CSPs, we should also consider changing the name of the org.moflon.tie package in the future.

Do you think, this could be done in a reasonable amount of time?

**Comment by RolandKluge** [comment]
Should be solved in eMoflon 2.26.0 (https://github.com/eMoflon/emoflon-tool/releases/tag/emoflon_2.26.0)
