### ISSUE TITLE
Ensure unique package prefix for packages in eMoflon developer workspace

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#181]
Every package that is publicly visible (i.e., exported in MANIFEST.MF) within the eMoflon developer workspace should start with org.moflon to avoid name clashes (cf. #180 ).

A cleaner solution would be to make the prefix of *generated* packages unique.
This holds for the following packages
* csp.constraints
* org.moflon.tie

@erhanleblebici FYI

**Comment by Arikae** [comment]
Done
