### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by georghinkel** [eMoflon/emoflon-tool#182]
Hi,

I would like to benchmark eMoflons TGG implementation in the State Charts to Petri Nets scenario I presented in an earlier ICMT paper [1]. However, repeatedly running `integrateForward` leads to a `ConcurrentModificationException`.  Am I missing something to wait for the last call to the `integrateForward` method or does this problem arise in eMoflon?

Here is the stack trace:
```
Exception in thread "main" java.util.ConcurrentModificationException
	at org.eclipse.emf.common.util.AbstractEList$EIterator.checkModCount(AbstractEList.java:758)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.doNext(AbstractEList.java:712)
	at org.eclipse.emf.common.util.AbstractEList$EIterator.next(AbstractEList.java:692)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.lambda$2(SynchronizationHelper.java:313)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.establishDelta(SynchronizationHelper.java:341)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.establishForwardDelta(SynchronizationHelper.java:288)
	at org.moflon.tgg.algorithm.synchronization.SynchronizationHelper.integrateForward(SynchronizationHelper.java:462)
	at org.moflon.tie.FiniteStatesToPetriNetsSync.main(FiniteStatesToPetriNetsSync.java:35)
```

This is the main method that is calling this:
```
	public static void main(String[] args) throws IOException {
		FiniteStatesToPetriNetsSync helper = new FiniteStatesToPetriNetsSync();
		String source = "instances/fsm.xmi";
		String delta = "instances/delta";
		helper.loadSrc(source);
		helper.integrateForward();
		long total = 0;
		for (int i = 0; i < 100; i++) {
			helper.setChangeSrc(helper.executeDeltaSpec(delta + Integer.toString(i) + ".xmi"));
			long startTime = System.nanoTime();
			helper.integrateForward();
			long endTime = System.nanoTime();
			total += (endTime - startTime);
		}
		System.out.println(total / 1000000);
	}
```

As a side question, would you consider the time measurement in that way as a fair comparison? The benchmark essentially generates a random input model and random modifications that mimic changes done by the user. The NMF solutions I am comparing eMoflon with perform these changes (each on a separate copy of the model) in memory and I measure the time to get an updated target model after each change. To get a good comparison, I transformed the changes into a series of delta specifications and would like to measure how long eMoflon takes to integrate all these changes separately. The time to serialize and deserialize these change specs should not be taken into account. As far as I have seen so far, eMoflon would load the delta spec in executeDeltaSpec, so that the time measurement would work as expected.

Best regards,

Georg Hinkel

**Comment by anthonyanjorin** [comment]
Hi Georg,

[side question: yes, the comparison sounds fair].

My wild guess would be that something is "wrong" with your delta specifications.
Could you visualise the problematic delta spec and paste the picture here?

To visualise a delta spec just open it with the normal reflective ecore model editor and make sure the PlantUML view in the eMoflon perspective is open.

Perhaps you are trying to delete a node that is being used by another part of the delta spec (e.g., an attribute delta)?  ```SynchronizationHelper.java:313``` handles deletion of nodes.

eMoflon could of course also just be buggy -- all our tests directly manipulate models to induce deltas, so delta specs are more part of a fancy feature for the end-user working with the delta editor, i.e., in the GUI (and is not covered by automatic unit tests).

Cheers,
Tony

**Comment by anthonyanjorin** [comment]
What do you think @erhanleblebici ?

**Comment by georghinkel** [comment]
Yes, I am able to open the delta specs in the reflective editor and of the 100 deltas, the first 5 or so run through. I attached the instances created by the last generator run.
[instances.zip](https://github.com/eMoflon/emoflon-tool/files/708861/instances.zip)

**Comment by georghinkel** [comment]
Ah, at the moment I do not have graphviz or dot installed, which means that I cannot render an image, though

**Comment by anthonyanjorin** [comment]
hmm...  To open them I need the source model fsm.xmi and the project with the metamodel (.ecore) too.  You could export the relevant part of your workspace with Eclipse.

**Comment by georghinkel** [comment]
Sorry, just forgot the metamodels. Here is the entire project.
[FiniteStatesToPetriNets.zip](https://github.com/eMoflon/emoflon-tool/files/708882/FiniteStatesToPetriNets.zip)

**Comment by anthonyanjorin** [comment]
Could you tell me which delta spec definitely does *not* work?

**Comment by anthonyanjorin** [comment]
Is this to be bidirectional?

**Comment by anthonyanjorin** [comment]
The rule ```EndStateToTransition``` is a bit problematic:  we treat attributes directly with their containing nodes, so ```isEndState := true``` in a context (black) node does not make much sense (unfortunately our editor doesn't complain -- it should!).  The correct rule looks like this:

<img width="281" alt="endstatetotransition" src="https://cloud.githubusercontent.com/assets/6302793/21990843/92e749b2-dc10-11e6-941e-d927cb7c7224.png">

But now only makes sense in the forward direction (hence my previous question).

**Comment by anthonyanjorin** [comment]
(have you tested the TGG to ensure that it behaves as you want it to?!  This makes sense before performing runtime measurements...)

**Comment by georghinkel** [comment]
It is meant to be bidirectional, though I have only tested the forward direction of the TGG implementation. The backward direction may be problematic, because the existence of a pattern in the RHS is reflected in an attribute on the LHS. I don't think (though I am not sure) that eMoflon could handle this, simply because there is no way to specify that it should change the attribute in case a pattern does no longer exist in the RHS. However, the performance comparison that I would like to make only uses the forward direction. I guess a fully bidirectional approach would be slightly more complex, but I guess this is somehow a limitation of eMoflon rather than a limitation of how the current extensions to TGGs.

The baseline I used originally for comparison is only unidirectional. Extending the paper now, I did not want to include a whole new example, but was asked to provide a runtime comparison with a bidirectional tool - the NMF Synchronizations solution of the example scenario is bidirectional - and therefore chose eMoflon because its textual language makes the comparison easier.

**Comment by anthonyanjorin** [comment]
err... sorry, the rule only makes sense in the bwd direction!  Ok - let me think about this for a few minutes.  I actually think it should be possible...  :)

**Comment by georghinkel** [comment]
For testing, so far I only tested whether states and transitions are all there and seem correctly transformed. I did not really check for the final states.

**Comment by anthonyanjorin** [comment]
Ok so it should be working now...  Some questions though:

In the example you seem to have a loop transition:

```
I was unable to collect any matches for  the following elements:
Nodes       (1):
	 [FiniteStateMachines.impl.TransitionImpl@247bddad (input: d)]
Edges       (4):
	 [FiniteStateMachines.impl.TransitionImpl@247bddad (input: d)] -endState-> [q9]
	 [FiniteStateMachines.impl.FiniteStateMachineImpl@2df3b89c (id: Test)] -transitions-> [FiniteStateMachines.impl.TransitionImpl@247bddad (input: d)]
	 [FiniteStateMachines.impl.TransitionImpl@247bddad (input: d)] -startState-> [q9]
	 [q9] -transitions-> [FiniteStateMachines.impl.TransitionImpl@247bddad (input: d)]
```

This is not described and is ignored by the TGG.

Do you want to handle such loops?

**Comment by anthonyanjorin** [comment]
Another question:  "dead-end transitions" in the Petri-net do not have any input (you do not set this in the rule).  Is that ok?

**Comment by anthonyanjorin** [comment]
Ok, assuming you want to handle loops, these 5 rules should do the trick (at least your one example works fine):

[Archive.zip](https://github.com/eMoflon/emoflon-tool/files/709023/Archive.zip)

**Comment by anthonyanjorin** [comment]
Ok, I'm studying ```delta5``` now, the first delta spec that fails.

Here are the reasons why:

1. For eopposite edges, only delete one of them in the delta spec.  The data structure is made for the ecore model editor where this would be impossible (sorry about that).
2. You have to be careful that your delta is actually "consistent".  This means that the result of applying  the delta should be a graph that can be generated by your TGG.  This is not the case for ```delta5``` as you end up with a transition in the air (which cannot be handled with your rules).  This is a feature not a bug (at least we see it this way):  Your synchroniser should reject things that cannot be propagated!  To make delta5 consistent you could delete the entire transition and all its incident edges.

In general, generating wild deltas is difficult and not necessarily interesting.   The two things we always measure are:

1.  Adding more and more, so propagating large deltas in a go.  You could just create deltas for 10, 100, 1000, .... (you actually don't need that many to get a feeling for how things scale in this regard).
2.  Adding the same thing (perhaps just one transition, but consistently!) in an increasingly large triple of consistent state machine and Petri net.  Here also only a few deltas but with significant difference in size and nature (deletion, creation, mixed) are necessary. 

Clearly things can be very different for different deltas, but what one typically wants are quality deltas where one knows exactly what is happening (as opposed to randomly generated deltas) which can produce wildly different results.

I hope that helps.

Cheers,
Tony

**Comment by anthonyanjorin** [comment]
This is how ```delta5``` could look like:

<img width="305" alt="delta5" src="https://cloud.githubusercontent.com/assets/6302793/21993635/2707a7f8-dc1c-11e6-8e57-fb78ac81f8ad.png">

Simply cutting it off from the resource tree should force the transition itself to be deleted, and all the rest of its incident edges too.

Btw:  If a delta spec fails you can always use our delta editor (right-click an XMI then choose open with delta editor) to perform the change yourself, save, and see what is created.

**Comment by anthonyanjorin** [comment]
A small comment:  you might want to divide by ```1000000.0``` and not by ```1000000``` to avoid integer division.

**Comment by georghinkel** [comment]
The deltas I generate actually do make sense but the problem was more their serialization. The hint that only one of the opposite edges has to be set and all references are reset automatically when an element is deleted from its container actually simplifies the code very much, because the very same steps are done in the in-memory model. The changes fall into one of the following categories: adding a state, adding a transition (with random start and end state), removing a state (and all of its transitions), removing a transition, renaming a state, renaming the machine, toggling whether a random state is an endstate. Because the effort to integrate these changes may vary, the benchmark basically generates 50 different change sequences and takes the average time of all change sequences.

Anyway, I got the benchmark working fine now, many thanks for your help. For eMoflon, the time for a change sequence similiar to the one I posted earlier is about 180ms for initial transformation and about 350ms for the change sequence where I have a lot of other programs running. If you are interested, I can post the entire results as soon as I have the benchmark running through all model sizes (this will probably be next week, though).

**Comment by anthonyanjorin** [comment]
Great job!  Yes, a plot would be very nice.  Especially as motivation for further optimisation when we see how much faster NMF is ;) 

BTW:  I hope to submit a bx benchmark to the upcoming TTC -- and of course expect an impressive NMF solution :D

**Comment by georghinkel** [comment]
The plot for small to medium-sized models is attached. There are actually two plots, one for the initial transformation and another one for running the 100 generated changes. Each data point is repeated 50 times, where a new state machine of the respective size and a new change sequence are generated in every measurement. For larger sizes, I get an OutOfMemory-Exception, presumably because the garbage collector is not fast enough discarding the generated Petri nets in teh batch solutions, but I will investiogate that further (currently, the benchmark also runs in 32bit). 

[updates.pdf](https://github.com/eMoflon/emoflon-tool/files/725907/updates.pdf)
[init.pdf](https://github.com/eMoflon/emoflon-tool/files/725908/init.pdf)

As you can see, the plot confirms your guess that the incremental NMF solution was faster than eMoflon, but at least for the largest size on the plot, the eMoflon solution is faster than the batch solutions, though they are somewhat tuned for speed. Here, incrementality pays off. Furthermore, the speedup of the incremental NMF solution compared to eMoflon decays from 122 to 22. I am really interested to see larger model sizes here.

**Comment by anthonyanjorin** [comment]
Thanks, Georg.  Yes, extending the plots to say a million states (make sure you provide enough memory) would be interesting for asymptotic behaviour.
