### ISSUE TITLE
Inheritance between types from different Ecore files is not working in MOSL

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-tool#187]
Hello,

I have a problem with inheritance between ObjectVariables in MOSL TGG rules. 

I have two input models for my TGG ``java.ecore`` and ``Modisco.ecore`` in the ``Modisco.ecore`` are some refinements for types from the ``java.ecore``

E.g. there is a type ``Model`` in the ``java.ecore`` file and a type ``MGravityModel`` in the ``Modisco.ecore`` file whose parent is ``Model``.

In the  TGG schema is the definition of the following correspondence:

```
ModelToTypeGraph {
#src-> Model
#trg-> TypeGraph
}
```

In a TGG rule I am specifying a creation of this correspondence type with a object variable ``mModel`` of the type ``MGravityModel`` as source:

```
#correspondence {
	++m:ModelToTypeGraph{
		#src->mModel
		#trg->tModel
	}
}
```

At this point the validator of the editor is marking the object variable ``mModel`` as wrong and is giving me the following error message:

``Couldn't resolve reference to ObjectVariablePattern 'mModel'.``

I attached the two source models, the target model, the schema file and the problematic TGG rule.

Best Sven
[ModelsAndTGG.zip](https://github.com/eMoflon/emoflon-tool/files/718865/ModelsAndTGG.zip)

**Comment by anthonyanjorin** [comment]
Did you list both packages as input (source) in the schema of the tgg?  This must be explicitly stated in the textual syntax.

**Comment by anthonyanjorin** [comment]
So I expect something like:
```
source {
  java
  modisco
}

target {
  typeGraph
}
```

**Comment by SvenPeldszus** [comment]
Yes, I did this:

´´´
#source {
	org.gravity.modisco.modisco
	java.java
}

#target {
	org.gravity.typegraph.basic.basic
}
´´´

The fully qualified name has been proposed by the auto completion,

**Comment by SvenPeldszus** [comment]
Sry, accidentally closed the issue.


However, I've just seen that there is some generated code for this rule, which looks correct at a first sight.

**Comment by anthonyanjorin** [comment]
errr...   so the editor is complaining but code is still being generated?!  Or have you now solved the problem with the additional source package...

**Comment by SvenPeldszus** [comment]
I haven't changed anything.

The editor is still complaining but there is code generated for these rules anyways.

**Comment by anthonyanjorin** [comment]
Ok - I'll take a look..

**Comment by anthonyanjorin** [comment]
Could you please export the relevant projects from Eclipse as zip so I can just import them?

**Comment by SvenPeldszus** [comment]
I attached the requsted zip file.

As a dependency MoDisco(Incubation) is needed which can be installed from Eclipse Modeling Components

[GRaViTY_MOSL_TGG.zip](https://github.com/eMoflon/emoflon-tool/files/719401/GRaViTY_MOSL_TGG.zip)

**Comment by anthonyanjorin** [comment]
I am unable to reproduce the error - looks fine for me.  The editor is happy, I can generate code, everything seems fine.  @Arikae or @erhanleblebici Could you try this out if you can reproduce the error?

**Comment by anthonyanjorin** [comment]
@SvenPeldszus could you tell me the exact version of eMoflon you're having the problem with?

**Comment by SvenPeldszus** [comment]
Ok, it was a problem with my version of eMoflon.

Thanks for your help.
