### ISSUE TITLE
Update eMoflon to depend on new Democles version

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#194]
Recent experiments by @anthonyanjorin revealed that it is a pain in the ... to work with eMoflon and a recent Democles target definition in parallel because several dependencies are in conflict.

It woule be nice to update the target def. used to build eMoflon based on Democlese 0.5.0.

@gervarro Do you see any major obstacles?

**Comment by gervarro** [comment]
@anthonyanjorin The standard trick is to move Democles 0.5.0 dependencies forward (ahead of standard eMoflon dependencies) as much as possible in the module that aims at using both.

> Do you see any major obstacles?

This depends on how major obstacles are interpreted. I am not conceptually against such an upgrade, however, the operation and template configurations have to be definitely updated, which is not rocket science in itself, but it is an error-prone task that influences the bootstrapping process (obviously in 2 Eclipse instances). Due to the long list of more important tasks, I cannot really promise my active participation in this upgrade in the near future.

**Comment by anthonyanjorin** [comment]
I don't understand what "moving dependencies forward" means.  The main problem I have right now is when starting a new client Eclipse instance from a host Eclipse instance with both eMoflon and Democles.  No matter what I do in the client, e.g., setting the target platform like in the client, things just don't work.

**Comment by RolandKluge** [comment]
@gervarro It appears to me that integrating the new Democles into eMoflon is indeed an important task to maintain compatibility with the eMoflon Ibex fork.
It would be great if you could point me at not-so-obvious possible pitfalls. 
I will give it a try during the upcoming eMoflon hacker days (https://github.com/eMoflon/emoflon-docu/wiki/Hacker-Days-2017-03)

My current strategy would be:
1. Checkout current Dev. workspace with current eMoflon version
2. Adjust *moflon.target* to Democles 0.5.0
3. Adjust feature version IDs of *org.gervarro....* features in *site.xml*
3. Change all dependencies from Democles 0.4.0 to Democles 0.5.0
4. Fix compiler errors
5. Commit to a dedicated branch (e.g., *rkluge-democles-0.5.0*)
6. Try to build the Dev. workspace (branch *rkluge-democles-0.5.0*) in a runtime Eclipse
   * Will I need to have a runtime-runtime Eclipse? I am unsure.
7. Create an eMoflon update site from inside the runtime Eclipse instance
   * This is probably a good candidate for changing the major version number to 3 :-)
8. Install this eMoflon in a very fresh Eclipse
9. Run auto-tests
   * For the *All modules* test case, take branch *rkluge-democles-0.5.0* of *emoflon-tool*
10. Everything is green in eMoflon land! :-)

@gervarro Did I miss out on something?

**Comment by gervarro** [comment]
> @gervarro Did I miss out on something?

Yes. Updating the dependencies from 0.4.0 to 0.5.0 is not sufficient as the configuration classes have to be adjusted as well. This latter is actually the most error-prone part.

> Will I need to have a runtime-runtime Eclipse?

Yes, I guess. The most important point is that you have to test whether bootstrapping works, which means that you have to check whether code generated in 2 Eclipse instances (old engine and new templates, new engine and new templates) perfectly match. (When I prepared the first version of the new bootstrapped engine, I carried out even a text compare on the generated code.) The other important thing that you have to consider is that the template (configuration) changes do not affect the current Eclipse instance, but the next one.

1. In the first Eclipse instance you can carry out the Steps 1-6, although Step 3 can probably be skipped at this stage, as site.xml only influences the update site generation. The most important part is that you have to configure the code generation properly (in a compilation error free and semantically correct manner).
2. In the second Eclipse instance, you can see / check whether the new templates can produce compilation error free code. Note that at this point you generated code with the new template setup, but you have not yet tested whether the freshly generated code is executable and semantically correct (i.e,. bootstrappable). You have to carry out the same configuration changes for the code generation as you did in the first Eclipse instance. (Your process is simplified in the sense that you change neither the specifications (eap files) nor the content of the templates, so you have a good chance that if the validation modules in the first (old code) and second (new code) Eclipse instances perfectly match, then they are going to be runnable.)
3. In my bootstrapping cycles I always started a third Eclipse instance as well to check whether the freshly generated code can run and generate itself (i.e., is bootstrappable) by comparing code in the workspace of the second and third Eclipse instances. In the end, both of the first 2 Eclipse instances will constitute the new v3.0 engine for which you can create an update site.

Steps 8-11 come after bootstrapping is OK.

**Comment by gervarro** [comment]
@RolandKluge For which date(s) are the Hacker Days planned / scheduled?

**Comment by RolandKluge** [comment]
@gervarro Thank you for the explanations. I guess, I'll try that!

The hacker days are planned for March 16+17, 2017.

**Comment by anthonyanjorin** [comment]
Was this attempted during the Hackerdays (just wondering)?
Working with Ibex is currently a nightmare due to this unfortunate version conflict :(

**Comment by RolandKluge** [comment]
No, unfortunately MOSL-GT stuff and other things took more time than expected.

**Comment by RolandKluge** [comment]
Further discussions showed that the effort/risk to migrate to the new Democles would probably not pay off in the near future. Closing.
