### ISSUE TITLE
Implement toString methods for control flow model elements

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#196]
While debugging the StringTemplates used for cMoflon, I was struggling with the default toString behavior of several classes of the control flow metamodel because, using ST::inspect, only the toString representation of objects is accessible.

**Comment by gervarro** [comment]
There is a possibility in StringTemplate to configure what should happen / be printed if an object of a certain type is rendered. The class/interface you have to implement is called `StringRenderer`.

**Comment by RolandKluge** [comment]
This is a valid solution, but I guess it would be nicer also during debugging, if we could provide an easy-to-understand implementation of toString for the most important classes.
