### ISSUE TITLE
Implement toString for StringTemplate-relevant classes in Democles toolchain

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#197]
(similar to #196)
While debugging the StringTemplates used for cMoflon, I was struggling with the default toString behavior of several classes of the Demcoles code generation infrastructure because, using ST::inspect, only the toString representation of objects is accessible.

Is it possible to update Democles 0.4.0 with toString implementation?
Otherwise, this could be a good reason to switch to Democles 0.5.0 at some point in time... (cf. #194)

I can remember the following:
- [ ] Chain
- ...

**Comment by RolandKluge** [comment]
@gervarro If this is OK for you, I could also implement the required toString methods. Can you tell me, which branch in the Democles repository to use as base for my contribution?

**Comment by gervarro** [comment]
As there

**Comment by RolandKluge** [comment]
Sorry, I don't understand.

**Comment by RolandKluge** [comment]
Will not be able to do this :-(
