### ISSUE TITLE
Missing source code for parts of the code generation 

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#198]
(applies for Democles 0.4.0)
I experienced that, using eMoflon, the source code of several Democles plugins is not shown (e.g., when accessing the GeneratorVariable class).

I will have to check whether this pertains to eMoflon's integration of Democles or to Democles 0.4.0 itself.

**Comment by gervarro** [comment]
This is an issue of the integration (i.e., when you prepare the update site for eMoflon). The Democles update site should contain the source code. Btw. I currently experiment with gradle to be able to produce maven/ivy/Eclipse update site artifacts in one run. If the process is ready, I will get rid of this ultra-low quality and undocumented Eclipse p2 infrastructure on the publishing side.

**Comment by RolandKluge** [comment]
Solved by adding the missing sources bundles.

I would be glad to here about the new build process you are experimenting with
