### ISSUE TITLE
Sign org.gervarro plugins

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#204]
Last month, we started to sign the features and plugins provided with eMoflon.

Currently, we only sign all features/plugins starting with org.moflon.

@gervarro Do you plan to sign org.gervarro-prefixed plugins as well? Currently, a warning is shown for these features/plugins when eMoflon is being installed.

**Comment by gervarro** [comment]
I think this is now the right time to raise this issue as I am planning to use gradle for the complete build process for Democles as well. Your earlier request to provide Maven descriptors is already integrated into the process. The new gradle build process is in a relatively advanced state, but I still have to test it on a smaller setup first, and then I can update the build process for Democles as well.

**Comment by RolandKluge** [comment]
Both (having signed plugins/features and Maven artefacts) would be really cool!

**Comment by RolandKluge** [comment]
Close because this is not an eMoflon-related issue.
