### ISSUE TITLE
MOSL-GT: Get rid of all these #'s

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#215]
Just as an experiment: We should try to get rid of all those hashes in the syntax.
Without them, the specification looks much cleaner.
We will coordinate this with the TGG guys:
```
import "platform:/resource/DemoLanguage/model/DemoLanguage.ecore"

package org.moflon.demo.doublelinkedlist

class List{
	operation findAnyNode() : Node {
		anyNode : Node
		invoke findAnyNodePattern(this:List, anyNode)
		return anyNode
	}
	
	pattern findAnyNodePattern(this:List, anyNode:Node){
	  this:List{
		- elements -> anyNode
	  }
    }
}
```

**Comment by anthonyanjorin** [comment]
Feel free to remove them :). The reason we have them is that we wanted to allow, e.g.,```import``` as a variable name (hence use #import as the keyword).
