### ISSUE TITLE
Refactor eMoflon website

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#218]
@Arikae We recently talked about restructuring the eMoflon website.

Personally, I find a one-page website cool (e.g., http://hufamo.compute.dtu.dk/)

It appears that Bootstrap is the framework the way to go to build lean and flexible websites:
https://startbootstrap.com/template-categories/all/

What do you think?

**Comment by RolandKluge** [comment]
Some links:
* https://blackrockdigital.github.io/startbootstrap-one-page-wonder/#
* https://github.com/BlackrockDigital/startbootstrap
* https://startbootstrap.com/template-overviews/simple-sidebar/
* http://bootsnipp.com/snippets/featured/link-to-top-page

**Comment by anthonyanjorin** [comment]
I'm all for bootstrap - using it myself for something else.

**Comment by RolandKluge** [comment]
Done since July.
