### ISSUE TITLE
Automatic installation of PlantUML not working anymore

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#229]
At the moment the automatic installation of PlantUML is not working anymore.

Either the associate sites entry is corrupt or we have to remove the version information in the dependencies (I think PlantUML's version is unfortunately "0.0.0" or similar).

**Comment by anthonyanjorin** [comment]
I think PlantUML has just changed the update site:  See: http://plantuml.com/eclipse

**Comment by RolandKluge** [comment]
When I tried out the installation of eMoflon 2.28.0 a few days ago, the automatic setup still worked fine.

I am not sure when I will be able to change the update site URL. Could take two weeks.

**Comment by anthonyanjorin** [comment]
This is even worse -- the interface has been changed so we have to adjust our usage of PlantUML :(

In general we need some kind of solution to this problem:  we have to somehow get a jar or similar and provide a stable update site ourselves.

**Comment by RolandKluge** [comment]
I have create a separate issue for the migration (#237) and close this issue since the installation currently works.
