### ISSUE TITLE
Latest version of eMoflon not backward compatible with existing TGG projects 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#230]
The latest version of eMoflon suddenly expects the xtext files to be at a different location than before (instead of src/org/moflon/tgg/mosl now src/<nameofproject>/org/moflon/tgg/mosl).

This breaks all existing TGG projects (I wonder how any single test is running).

**Comment by anthonyanjorin** [comment]
Found this in the changelog:

> Old specifications remain compatible: The MOSL-TGG builder searches for any file named Schema.tgg in the /src folder

Doesn't work though.

**Comment by anthonyanjorin** [comment]
If I may say so this is also a very ugly change:  (1) it violates normal Java package naming conventions, (2) renaming the project becomes quite problematic (refactoring in Eclipse won't help)

**Comment by anthonyanjorin** [comment]
Lastly, it is inconsistent as our attribute condition file  `AttributeCondDefLib` still at its old position (right?).

**Comment by RolandKluge** [comment]
> Old specifications remain compatible: The MOSL-TGG builder searches for any file named Schema.tgg in the /src folder

Yes, this was may plan, originally, but I failed to fully reverse engineer the way in which TGG schema and rules are loaded.
@Arikae Maybe we should invest a little more effort to support any location for Schema.tgg files? Maybe we find a safe way to identify the "root" .tgg file that contains the schema definition.

**Comment by anthonyanjorin** [comment]
btw. I relocated my Schema.tgg file and it still didn't work.  So basically all .tgg files in the project have to be relocated (strangely apart from the attribute condition library file).

**Comment by RolandKluge** [comment]
@Arikae Could you check that?

**Comment by Arikae** [comment]
Yup, I'll try to fix it

**Comment by anthonyanjorin** [comment]
Hi guys, 

We've sent in a TTC proposal and this would mess up the installation instructions.

Please fix ASAP :)

**Comment by erhanleblebici** [comment]
fixed. As from now, there is no naming conventions for the tgg files and their packages. The only assumption is that all tgg files are in your src folder.

If you immediately need a build with the fix, take mine: https://www.dropbox.com/sh/z6x1ni4xxdzno5a/AACzqwPCTjSVwwL3nTqXY_O1a?dl=0
