### ISSUE TITLE
Migrate to new version of PlantUML

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#237]
As mentioned in #229, the API of PlantUML has changed with the new official version.

We will have to migrate to the new API in the near future and adjust the referenced update site accordingly: http://plantuml.com/eclipse

**Comment by anthonyanjorin** [comment]
I have now switched for Ibex.  Should be doable.

**Comment by RolandKluge** [comment]
Link to Merge: eMoflon/emoflon-ibex/pull/162
