### ISSUE TITLE
Reduce ANTLR dependency to 3.2

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-tool#251]
I just found out that tgg projects are having a dependency to ANTLR 3.5.2 which is pretty bad when you want to use Xtext because Xtext only uses 3.2.0 and is pretty much incompatible to all other version.
Apparently the dependency seems to come from org.moflon.core.utilities but I wasn't able to find out why and how.
However, when someone wants to use Xtext within a project with a dependency to utilities, he will run into unexpected EOF token exceptions and such which happened to me.

**Comment by RolandKluge** [comment]
As long as I have been working on eMoflon, Antlr has been a central dependency, which is indeed bad. In the next months, we will work on eliminating Antlr dependencies.

**Comment by RolandKluge** [comment]
@Arikae Is this still important to you?
