### ISSUE TITLE
Market place installation per drag and drop not working for Eclipse Neon 3

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#252]
With the latest version of Eclipse (Neon 3, just tried it out a minute ago), installation via the market place and drag&drop does not work.

**Comment by RolandKluge** [comment]
@anthonyanjorin Do you get a specific error message?

I experienced problems with the marketplace in the past as well. Some went away after some time.

I will analyze the problem as soon as I have some time.

**Comment by RolandKluge** [comment]
The Marketplace log tells the problem (https://marketplace.eclipse.org/content/error/report/3420957):
```
Cannot complete the install because one or more required items could not be found. Software being installed: eMoflon MOSL-TGG 2.30.0.201704132021 (org.moflon.tgg.mosl.feature.feature.group 2.30.0.201704132021) 
Missing requirement: org.moflon.ide.core 2.2.0.201704132021 (org.moflon.ide.core 2.2.0.201704132021) requires 'bundle org.eclipse.jgit 4.4.0' but it could not be found 
Cannot satisfy dependency: From: eMoflon Core (required) 2.30.0.201704132021 (org.moflon.ide.feature.feature.group 2.30.0.201704132021) To: org.moflon.ide.core [2.2.0.201704132021] 
Cannot satisfy dependency: From: eMoflon MOSL-TGG 2.30.0.201704132021 (org.moflon.tgg.mosl.feature.feature.group 2.30.0.201704132021) To: org.moflon.ide.feature.feature.group 2.12.0
```

**Comment by anthonyanjorin** [comment]
My error is now (with Neon.3):  Not compatible with this version of Eclipse

**Comment by anthonyanjorin** [comment]
We should just remove it from the website for the time being if it doesn't work

**Comment by RolandKluge** [comment]
I added a remark to https://emoflon.github.io/installation.html and commented the "Install" button.
