### ISSUE TITLE
Local Completeness Exception in MOSL Editor/Validation

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-tool#254]
Hello,

I started to work on this years TTC case and I am getting the following Local Completeness Exception:

``11:53:59 ERROR [synchronization.SynchronizationHelper::518] - Your TGG codeadapter is not translation locally complete!
This means I was unable to translate the input graph without backtracking.
This is usually due to TGG rules that do not have enough context information in the input component to guarantee the required context in the correspondence and output components when translating.
Please consider your TGG carefully and make sure that all context elements in the output component can be implied from the input context elements of each rule.
I got stuck while trying to extend the following source matches: [LinkVariablePatternEdgeToTGGLinkVariableEdgeRule]``

also my rule contains the error: `Couldn't resolve reference to ObjectVariablePattern 'cosem'.`

The rule is:

``#source { 
	cosem : COSEMRoot {
	}
	cim :CIMRoot{
	}
	root : Root {
		-cosem->cosem
	}
}
``

I am not sure if the glue model I defined between the COSEM and the CIM model is the problem or if this is an eMoflon bug. However, if the first one is the problem there should be at least an understandable error message.

I attached my TGG project including al relevant models: [TCC17-EMoflonTGGSolutionv0a.zip](https://github.com/eMoflon/emoflon-tool/files/992923/TCC17-EMoflonTGGSolutionv0a.zip)

Already in advance many thanks for your help.

**Comment by erhanleblebici** [comment]
For anyone who wants to investigate that further:

A break point in TGGScopeProvider::is_equal_or_super_type_of_ov and trigerring code completion (Strg+space) for the '-cosem-->' edge shows that COSEM.ecore has been loaded twice. The expected type of the edge and the type of the cosem ov are not the same => Validation Error in Editor

**Comment by anthonyanjorin** [comment]
This hack solves the problem (not sure if it is a fix though):

Change this:
```
def is_equal_or_super_type_of_ov(EClass sup, IEObjectDescription desc){
		var sub = (desc.EObjectOrProxy as ObjectVariablePattern).type
		return sub.equals(sup) || sub.EAllSuperTypes.contains(sup) || EcorePackage.eINSTANCE.EObject.equals(sup)
	}
```

to:

```
def is_equal_or_super_type_of_ov(EClass sup, IEObjectDescription desc){
		var sub = (desc.EObjectOrProxy as ObjectVariablePattern).type
		return MoflonUtil.getFQN(sub).equals(MoflonUtil.getFQN(sup)) || 
			   !sub.EAllSuperTypes.filter[st | MoflonUtil.getFQN(st).equals(MoflonUtil.getFQN(sup))].empty || 
			   EcorePackage.eINSTANCE.EObject.equals(sup)
	}
```

@erhanleblebici You can decide if you want to commit this.  Unfortunately I couldn't understand _why_ the objects are getting loaded multiple times.

**Comment by anthonyanjorin** [comment]
This has been sort of resolved or at least avoided.
