### ISSUE TITLE
eMoflon forgets validation timeout

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-tool#256]
Hello, my eMoflon continuously forgets the manually configured validation timeout.

For one of my projects I have to increase the validation timeout to at least 90 seconds but after a restart eMoflon restores always the 30s default validation timeout.

Furthermore, the validation timeout of 30s was also in other projects too short. Therefore, I suggest to increase the default timeout to 120s or maybe even higher values like 300s.

Thanks

**Comment by RolandKluge** [comment]
Confirmed for 2.29.0
