### ISSUE TITLE
Democles: Where is generateReverseSearchPlan?

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#278]
@gervarro: I have now figured out that CompilerPatternMatcherModule (0.5.0) is a syntactically suitable replacement for CompilerPatternBuilder (0.4.0).
However, looking at the following code, I cannot figure out how to generate a 'reverse search plan' using this class:
https://github.com/eMoflon/emoflon-tool/blob/master/org.moflon.sdm.compiler.democles/src/org/moflon/compiler/sdm/democles/PatternMatcherCompiler.java#L50

Can you help me?

**Comment by gervarro** [comment]
It is always a good idea to check out the corresponding test project (`org.gervarro.democles.compiler.test`) to see what a complete configuration looks like. There are only few locations where the semantics changed. In all the other cases I carried out only renaming to unify the terminology in the compiler and in the batch and incremental interpreter, and your guesses are correct.

**Comment by RolandKluge** [comment]
OK, I could not find the compiler test on /trunk or a branch for version 0.5.0.
But, looking at *org.gervarro.democles.codegen.stringtemplate.test* appears to be suitable.
The code in *rkluge-dev-democles1* appears to be similar.
Apparently, I broke something else...
