### ISSUE TITLE
Handbook on Overleaf with live links from the website?

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#36]
_From @anthonyanjorin on April 20, 2016 19:27_

How about we host our handbook on Overleaf and link directly from the website to a read-only version provided by Overleaf?

This way:
+ working on the handbook would be really easy
+ any updates are immediately available from the website without us doing anything at all (no release step any longer)

What do you think?  @RolandKluge @erhanleblebici 

_Copied from original issue: eMoflon/emoflon#695_

**Comment by RolandKluge** [comment]
I think, this is a good idea. My experience with Overleaf was that the re-rendering may take some time (but maybe not much longer than on a laptop PC).

I especially like the idea that the handbook is always up-to-date.

If somebody would be willing to try this out (maybe also a HiWi?), then we should do it.

**Comment by RolandKluge** [comment]
We may run into problems here because all handbook parts rely on a common (seventh) project. In Overleaf, however, all projects are isolated from one another. There is no chance to define 'crossreferences': https://support.overleaf.com/forums/137318-feedback/suggestions/6925401-is-it-possible-to-use-external-references-between

**Comment by erhanleblebici** [comment]
Having GitHub for our collaboration (which works well so far), we give up this effort of having one more component in the release chain
