### ISSUE TITLE
Jpeg export from plantUML pictures is broken

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#62]
_From @SchroedingersCatIsUndead on August 19, 2016 12:47_

the pictures look like this 
![jpegpicture](https://cloud.githubusercontent.com/assets/9741282/17810166/cc4eaee0-661b-11e6-9c48-9ecd8cc26ac5.jpg)

_Copied from original issue: eMoflon/emoflon#773_

**Comment by RolandKluge** [comment]
@SaschaEdwinZander Is this issue still relevant?

**Comment by SaschaEdwinZander** [comment]
yes and no.
Now I get an error if I try to save it as a jpg
![error](https://cloud.githubusercontent.com/assets/9741282/19887011/4eee0d02-a026-11e6-9903-7e007a159827.png)

I think we should disable jpeg export anyway

**Comment by RolandKluge** [comment]
OK, could you do that?

**Comment by SaschaEdwinZander** [comment]
I can try it, there are some hints from plant uml to do it.
