### ISSUE TITLE
Remove migration routines of new build process

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#69]
_From @RolandKluge on August 28, 2016 13:9_

The execution of the natureAndBuilderConfiguratorTask should be removed when the order of builders has been fixed in the eMoflon developer workspace.

In org.moflon.ide.core.runtime.OpenProjectHandler.run(IProgressMonitor)

_Copied from original issue: eMoflon/emoflon#784_

**Comment by RolandKluge** [comment]
Locations:
* org.moflon.core.propertycontainer.MoflonPropertiesContainerHelper.updateMoflonPropertiesToNewBasePackage(IProject)
* org.moflon.tgg.mosl.builder.MOSLTGGProjectMigrator
* org.moflon.ide.core.NatureMigrator
* org.moflon.autotest.core.WorkspaceInstaller.installPsfFiles(...).new ImportProjectSetOperation() {...}.run(IProgressMonitor)

**Comment by gervarro** [comment]
Hava all of our users (Johannes, Sven, ...) already switched to our latest build process?

**Comment by RolandKluge** [comment]
eMoflon 2.24.0 is the last release that supports the automatic migration.
Necessary steps are documented in the changelog.txt

**Comment by RolandKluge** [comment]
MOSLTGGProjectMigrator is removed in @e32fbfec00f25
NatureMigrator is removed in @ec4570805

**Comment by RolandKluge** [comment]
Closed.
