### ISSUE TITLE
Use the Eclipse marketplace

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#78]
_From @anthonyanjorin on September 9, 2016 14:26_

The latest and coolest way to install an Eclipse plugin is to drag and drop a "button" from a website onto a running instance of Eclipse.   No idea how this works, but it has something to do with the Eclipse marketplace.  Perhaps we should some time in the future move from our old school update sites to this? 

_Copied from original issue: eMoflon/emoflon#802_

**Comment by RolandKluge** [comment]
Does not seem to be too difficult but I would wait until eMoflon has moved to GitHub completely:

https://marketplace.eclipse.org/quickstart

**Comment by anthonyanjorin** [comment]
Can't we close this now?

**Comment by RolandKluge** [comment]
I see that you are hunting for closable issue. 👍 

Indeed, we can close this since eMoflon is now installable from the Eclipse Marketplace: https://marketplace.eclipse.org/content/emoflon
