### ISSUE TITLE
Generated ecore in TGG projects should use platform:/plugin or platform:/resource URIs

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#81]
_From @anthonyanjorin on September 15, 2016 7:35_

_Copied from original issue: eMoflon/emoflon#808_

**Comment by anthonyanjorin** [comment]
Tip from Greg:  Wenn die Metamodelle durch die *Dependency geladen werden, dann einfach von den Parametern (true,true) auf (true, false) wechseln.

**Comment by RolandKluge** [comment]
@anthonyanjorin Is this still relevant?
