### ISSUE TITLE
no-auto option for IntegrationBuilder doesn't seem to be working

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#82]
_From @anthonyanjorin on September 15, 2016 8:43_

Even though I have disabled the IntegrationBuilder for auto-builds (and I see a nice [no-auto] label on the project), code is still generated when I save .tgg files.  I don't seem to notice any difference at all in the builder behaviour... 

_Copied from original issue: eMoflon/emoflon#810_

**Comment by RolandKluge** [comment]
This is strange - apparently it worked some time ago, but indeed it does not working now.

One issue that I find annoying is that (e.g.,) cspcodeadapter is build due to being a recursive dependency of another project, which is auto-built.

**Comment by anthonyanjorin** [comment]
Still not working in the latest version.  Almost impossible to work with the mosl codeadapter project as it starts building even if you change Java files that have nothing to do with the TGG itself.

**Comment by RolandKluge** [comment]
Indeed, this should be a top-priority task because otherwise working with the dev workspace will eventually become impossible - I also experiences this. Maybe we should relax the rebuilding rules a little.

**Comment by gervarro** [comment]
> Still not working in the latest version. Almost impossible to work with the mosl codeadapter project as it starts building even if you change Java files that have nothing to do with the TGG itself.

Could you please describe the exact context more precisely? Which is the 'latest' version? Do you change Java files in the src directory of the mosl codeadapter project?

I did not experience any auto-build problems with the version I have on my desktop, which might obviously be different from what you have. I would like to reproduce this bug.

**Comment by anthonyanjorin** [comment]
I installed from https://emoflon.github.io/eclipse-plugin/emoflon_2.19.0/update-site2/ 

To reproduce change some Java files (e.g., in org.moflon.tgg.mosl.codeadapter/org.moflon.tgg.mosl.builder) and save.

That should trigger a new build of the project.

**Comment by RolandKluge** [comment]
Does this pertain to 2.20.0 as well?

**Comment by RolandKluge** [comment]
I guess, this should be fixed now, right?
