### ISSUE TITLE
Visualization of EPackages and EClasses in .ecore

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#85]
It is nice to have a view in PlantUML, where the Relations of EClasses in an EPackage can be seen.
A view for EClasses with their references, attributes and methodes also would be fine

**Comment by SchroedingersCatIsUndead** [comment]
done in commit 89e5ca7ba1be289f41bb51e3380da74ad6060425

**Comment by SchroedingersCatIsUndead** [comment]
sry wrong issue

**Comment by SaschaEdwinZander** [comment]
done in #106
