### ISSUE TITLE
Caching not working for visualisation of abstract rules 

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#88]
To reproduce:

Open an abstract rule in the TGG editor, and make sure "do not flatten refinements" is not chosen.

If you now move the cursor around in the file, you'll notice that the visualisation is being re-generated every time. For all other visualisations, a cache is used to avoid this. The cache is only invalidated when the editor is saved.

Using a cache is important for two reasons: (1) it keeps the picture stable (now its jumping about), and (2) for large patterns dot takes a while to regenerate the picture.

@anthonyanjorin FYI

**Comment by SchroedingersCatIsUndead** [comment]
solved in 86c8e0312a75ae762718e785af1f443e60938209
