### ISSUE TITLE
MOSL bwd transformation is not working

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#95]
One problem is that the resourceSet must be enriched with mappings for projects in the workspace using `org.moflon.util.plugins.manifest.PluginURIToResourceURIRemapper`

Another problem is that we do not have any tests checking that this still works after changing things.

**Comment by gervarro** [comment]
I do not know where MOSL bwd transformation is invoked, but you can use 
`final IProject project = ResourcesPlugin.getWorkspace().getRoot().getProject(saveTargetName);
CodeGeneratorPlugin.createPluginToResourceMapping(resourceSet, project);`
at the corresponding location.
