### ISSUE TITLE
Add at least one test to ensure that "foreign" metamodels work for MOSL/TGGs

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#96]

**Comment by RolandKluge** [comment]
Is this the example provided by Sven?

**Comment by anthonyanjorin** [comment]
hmm...  yes, Svens TGG could also serve as an example for this (so EA /and/ foreign metamodel)

**Comment by RolandKluge** [comment]
This has been solved in #137
