### ISSUE TITLE
TGG Export from EA is broken

### ISSUE THREAD

**Issue by SvenPeldszus** [eMoflon/emoflon-tool#97]
Hi,

with the current eMoflon Version 2.20 (and all after 2.16) the export of TGGs from EA is broken.

Toni already located the Problem but unfortunately was unable to fix it:

The exported *.pre.ecore has a wrong nsURI.

Currently the nsURI is st to "... .pre.ecore" but it should be "... .ecore". In the pre.ecore file generated by xtext Projects the nsURI is also without the "pre". This bug located somewhere in the EA export.

It would be nice if you fix this soon, as I still have to work with EA.

Thanks, Sven

**Comment by anthonyanjorin** [comment]
The does not directly have anything to do with the EA export (in C#), but more with the transformation to Ecore (and actually just the way URIs are set and the file name is fixed).

**Comment by gervarro** [comment]
Fixed by [https://github.com/eMoflon/emoflon-tool/commit/b3ee4795e338fac9454660428893e4c4e47d6e73](url)
